#!/bin/bash

if [ -z "$1" ] || [ -z "$2" ]
then
	printf "#######################
 Extracts BAF and LRR values for a single individual on the desired chromosome.
 Plots can be generated by Shiny (indicate 1 to launch it, default 0).
 The range can be optionally limited with posmin and posmax arguments.
 USAGE:
 ./baf_extractor_query.sh ChipID Chromosome [WantPlots=1/0, PosMin, PosMax]
#######################\n"
	exit 1
fi

u=$1
c=$2
shiny=${3:-0}
pmin=${4:-0}
pmax=${5:-270000000}

out="/tmp/output_baf.csv"

read -s -p "DB user pass: " pp
echo ""

echo "Selecting SNPs on chromosome ${c} between positions ${pmin} and ${pmax} for individual with Chip ID ${u}."
echo "Output will be written to output file ${out}."

mysql -uroot -p${pp} moba_baf -B -e \
	"SELECT r.uid, chr, pos, rsid, baf, lrr
	FROM ukey
	INNER JOIN raw${c} r ON ukey.uid=r.uid
	INNER JOIN snpkey ON snpkey.snpid=r.snpid
	WHERE chipid=\"${u}\"
	AND pos>${pmin} AND pos<${pmax};" > ${out}

awk -v c=${c} -v u=${u} -v minp=${pmin} -v maxp=${pmax} '$1==c && $7==u && $3>minp && $2<maxp' /home/julius/Desktop/MoBa_BAF/ALL_CALLS_nosdfilter_nice.rawcn > ${out}_calls

awk -v c=${c} -v minp=${pmin} -v maxp=${pmax} '$3=="chr"c && $8>minp && $7<maxp{print $2, $7, $8, $13}' /home/julius/soft/inrich/refs/ucsc_ref_hg38.map > ${out}_genes

if [ "$shiny" -eq 1 ]
then
	echo "Visit 192.168.0.133:3535 to inspect the results."
	echo "Don't forget to close the app after inspecting!"
	./baf_extractor_plotter.R
fi
